# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/Constraints.xdc

# Block Designs: bd/CPU/CPU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU || ORIG_REF_NAME==CPU} -quiet] -quiet

# IP: bd/CPU/ip/CPU_processing_system7_0_0/CPU_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_processing_system7_0_0 || ORIG_REF_NAME==CPU_processing_system7_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_MaybeThisWillWork_0_0/CPU_MaybeThisWillWork_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_MaybeThisWillWork_0_0 || ORIG_REF_NAME==CPU_MaybeThisWillWork_0_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_ps7_0_axi_periph_0/CPU_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_ps7_0_axi_periph_0 || ORIG_REF_NAME==CPU_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_rst_ps7_0_100M_0/CPU_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_rst_ps7_0_100M_0 || ORIG_REF_NAME==CPU_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/CPU/ip/CPU_auto_pc_0/CPU_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CPU_auto_pc_0 || ORIG_REF_NAME==CPU_auto_pc_0} -quiet] -quiet

# XDC: bd/CPU/CPU_ooc.xdc
