# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/FPGALabGroupName/FinalProject/FinalProject.srcs/sources_1/bd/CPU/ip/CPU_rst_ps7_0_100M_0/CPU_rst_ps7_0_100M_0.xci
# IP: The module: 'CPU_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGALabGroupName/FinalProject/FinalProject.srcs/sources_1/bd/CPU/ip/CPU_rst_ps7_0_100M_0/CPU_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGALabGroupName/FinalProject/FinalProject.srcs/sources_1/bd/CPU/ip/CPU_rst_ps7_0_100M_0/CPU_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/FPGALabGroupName/FinalProject/FinalProject.srcs/sources_1/bd/CPU/ip/CPU_rst_ps7_0_100M_0/CPU_rst_ps7_0_100M_0.xci
# IP: The module: 'CPU_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/FPGALabGroupName/FinalProject/FinalProject.srcs/sources_1/bd/CPU/ip/CPU_rst_ps7_0_100M_0/CPU_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/FPGALabGroupName/FinalProject/FinalProject.srcs/sources_1/bd/CPU/ip/CPU_rst_ps7_0_100M_0/CPU_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'CPU_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
